### ISSUE TITLE
After "Error saving blobs" no retry possible?

### ISSUE THREAD

**Issue by meinname** [codsane/autotss#1]
Hi,

i want to run autotss on a regular basis to download shsh2 for 7 devices.
But sometimes i get "Error saving blobs".
And on the next run of autotss i get "No new firmwares being signed..."

So i delete the devices.db and start the script again. But this time other blobs get the error.
I tried it about 20 times and never had a run with all blobs for every signed firmeware.

Can't the script be modified to be able to retry previous failed downloads?

**Comment by codsane** [comment]
autotss has been rewritten since this issue, you may want to take a look again and see if your issues have been resolved.
