### ISSUE TITLE
Does not find tsschecker

### ISSUE THREAD

**Issue by Jakesta13** [codsane/autotss#10]
Hello,
I was giving this program a go and it refuses to find tsschecker or tsschecker_macos, even if directly targeted in command arguments.

This is on Windows

**Comment by leftyfl1p** [comment]
Please share the full command you are passing. Also, the Mac binary isn’t going to work on windows.

**Comment by Jakesta13** [comment]
> Please share the full command you are passing. Also, the Mac binary isn’t going to work on windows.

`\path\to\python3.exe autotss.py`

I extracted the entire source of tsschecker into autotss-master's folder and autotss would complain it couldn't find 'tsschecker' and to try '-p \path\to\tsschecker\tsschecker-macos'
Noticing that tsschecker-macos was directly in the folder with autotss-master I ran:
`\path\to\python3.exe autotss.py -p \path\to\autotss-master\tsschecker-macos`

I also tried tsschecker without -macos, I checked all the folders from tsschecker and couldnt figure out what it was complaining about.

**Comment by leftyfl1p** [comment]
Have you ran tsschecker independently? I think you’re trying to use the Linux and mac versions on windows which isn’t going to work.

**Comment by Jakesta13** [comment]
> Have you ran tsschecker independently? I think you’re trying to use the Linux and mac versions on windows which isn’t going to work.

You know what, I just noticed that the latest release of TssChecker is for only Mac OS and the Release before that one is for all OSs.
I'll give it a go, and if it works I'll close the issue.


If anyone else has this problem on windows, they first have to look for "`tsschecker_v[Version]_mac_win_linux.zip`" when downloading.

**Comment by Jakesta13** [comment]
> > Have you ran tsschecker independently? I think you’re trying to use the Linux and mac versions on windows which isn’t going to work.
> 
> You know what, I just noticed that the latest release of TssChecker is for only Mac OS and the Release before that one is for all OSs.
> I'll give it a go, and if it works I'll close the issue.
> 
> If anyone else has this problem on windows, they first have to look for "`tsschecker_v[Version]_mac_win_linux.zip`" when downloading.

Ok, It looks like it needs to be manually built from source to work on windows, as the previous version is marked as too old, and the only other posted release is for MacOS, including the one directly linked in the README.md
I'll give it a shot and I guess drop that file here for future ref

**Comment by leftyfl1p** [comment]
Closed as solved.
