### ISSUE TITLE
No Blobs Saved

### ISSUE THREAD

**Issue by ghost** [codsane/autotss#4]
It creates version folders with no blobs inside.

**Comment by sohsatoh** [comment]
my fork would resolve this problem.

**Comment by ghost** [comment]
I've tried both the original and your fork, neither are working. I've tried using my own devices.ini and the example one (after being renamed from example to devices.ini) It still doesn't work.

**Comment by sohsatoh** [comment]
Odd..
Did python give you error messages?
And could you give me your devices.ini?

**Comment by ghost** [comment]
/Terminal/-

Justins-MacBook-Pro:~ justinwhite$ cd Documents
Justins-MacBook-Pro:Documents justinwhite$ ls
FutureRestore	autotss
Justins-MacBook-Pro:Documents justinwhite$ cd autotss
Justins-MacBook-Pro:autotss justinwhite$ ls
README.md		devices.ini
autotss.py		tsschecker_macos
Justins-MacBook-Pro:autotss justinwhite$ python3 autotss.py
Checking devices.ini for new devices...
Device: [iPhone5S] ECID: [48F29442C78] Board Config: [N51AP]
Device: [iPhone6] ECID: [126518307B5026] Board Config: [n61ap]
Added 2 new devices to the database

Saving unsaved blobs for 2 devices...
Device: [iPhone6,1] Version: [11.2.2]
Device: [iPhone6,1] Version: [11.2.1]
Device: [iPhone6,1] Version: [11.2]
Device: [iPhone7,2] Version: [11.2.2]
Device: [iPhone7,2] Version: [11.2.1]
Device: [iPhone7,2] Version: [11.2]
Done saving blobs

Updating database with newly saved blobs...
Done updating database
Justins-MacBook-Pro:autotss justinwhite$ 


/devices.ini/-

[iPhone5S]
identifier = iPhone6,1
ecid = 48F29424C78
boardconfig = N51AP

[iPhone6]
identifier = iPhone7,2
ecid = 126536107B6026



EDIT: I had to remove the database and version folders from where I tried using the example devices and repost the log

**Comment by sohsatoh** [comment]
After removing the database, do you still have the problem?
And if you have, which (or both) device cannot you saved?

Also, could you run it?
```
cd ~/Documents/autotss
cat autotss.py
```

**Comment by ghost** [comment]
Last login: Tue Jan 23 11:16:56 on ttys000
Justins-MacBook-Pro:~ justinwhite$ cd ~/Documents/autotss
Justins-MacBook-Pro:autotss justinwhite$ cat autotss.py
import requests as r
import configparser
import subprocess
import dataset
import json
import os
import io


class autotss:

    def __init__(self):
        self.liveFirmwareURL = 'https://api.ipsw.me/v2.1/firmwares.json/condensed'
        self.liveFirmwareAPI = None
        # self.otaFirmwareURL = 'https://api.ipsw.me/v2.1/ota.json/condensed'
        # self.otaFirmwareAPI = None
        self.database = dataset.connect('sqlite:///autotss.db')

        self.importNewDevices()
        self.devices = [row for row in self.database['devices']]
        self.checkAllDevices()
        self.pushToDatabase()

    def importNewDevices(self):
        """ Checks devices.txt for new entries. Parses entries and
        inserts them into the devices table in our database """

        print('Checking devices.ini for new devices...')
        db = self.database['devices']
        newDevices = []
        numNew = 0

        # Check to make sure devices.ini exists, otherwise warn and continue without new devices
        if os.path.isfile('devices.ini'):
            config = configparser.ConfigParser()
            config.read('devices.ini')
            for section in config.sections():
                name = section
                identifier = config.get(section, 'identifier').replace(' ','')
                ecid = config.get(section, 'ecid')

                try:
                    boardconfig = config.get(section, 'boardconfig')
                except:
                    boardconfig = ''
                if not boardconfig:
                    boardconfig = self.getBoardConfig(identifier)

                newDevices.append({'deviceName': name, 'deviceID': identifier, 'boardConfig': boardconfig, 'deviceECID': ecid, 'blobsSaved': '[]'})
        else:
            print('Unable to find devices.ini')

        # Add only new devices to database
        for newDevice in newDevices:
            print('Device: [{deviceName}] ECID: [{deviceECID}] Board Config: [{boardConfig}]'.format(**newDevice))
            if not db.find_one(deviceECID=newDevice['deviceECID']):
                numNew += 1
                db.insert(newDevice)
        print('Added {} new devices to the database'.format(str(numNew)))

        return

    def getBoardConfig(self, deviceID):
        """ Using the IPSW.me API, when supplied a device identifier
        the relevant board config will be returned. The request to
        IPSW.me will be stored as `self.liveFirmwareAPI` to avoid
        unneeded repeated calls to the IPSW.me API. """

        if not self.liveFirmwareAPI:
            self.liveFirmwareAPI = self.removeUnsignedFirmwares(r.get(self.liveFirmwareURL))
        return self.liveFirmwareAPI[deviceID]['BoardConfig']

    def checkForBlobs(self, deviceECID, buildID):
        """ Checks against our database to see if blobs for a
        device have already been saved for a specific iOS version.
        The device is identified by a deviceECID, iOS version is
        identified by a buildID. """

        deviceInfo = self.database['devices'].find_one(deviceECID=deviceECID)

        for entry in json.loads(deviceInfo['blobsSaved']):
            if entry['buildID'] == buildID:
                return True

        return False

    def removeUnsignedFirmwares(self, rawResponse):
        """ Taking the raw response from the IPSW.me API, process
         the response as a JSON object and remove unsigned firmware
         entries. Returns a freshly processed devices JSON containing
         only signed firmware versions. """

        deviceAPI = rawResponse.json()['devices']

        ''' Rather than messing around with copies, we can loop
         through all firmware dictionary objects and append the
         signed firmware objects to a list. The original firmware
         list is then replaced with the new (signed firmware only) list.'''
        for deviceID in deviceAPI:
            signedFirmwares = []
            for firmware in deviceAPI[deviceID]['firmwares']:
                if firmware['signed']:
                    signedFirmwares.append(firmware)
            deviceAPI[deviceID]['firmwares'] = signedFirmwares

        return deviceAPI

    def checkAllDevices(self):
        """ Loop through all of our devices and grab matching
        device firmwares from the firmwareAPI. Device and
        firmware info is sent to saveBlobs(). """

        print('\nSaving unsaved blobs for {} devices...'.format(str(len(self.devices))))
        for device in self.devices:
            for firmware in self.liveFirmwareAPI[device['deviceID']]['firmwares']:
                self.saveBlobs(device, firmware['buildid'], firmware['version'])

        print('Done saving blobs')

    def saveBlobs(self, device, buildID, versionNumber):
        """ First, check to see if blobs have already been
        saved. If blobs have not been saved, use subprocess
        to call the tsschecker script and save blobs. After
        saving blobs, logSavedBlobs() is called to log that
        we saved the device/firmware blobs. """

        if self.checkForBlobs(device['deviceECID'], buildID):
            return True

        print('Device: [{}] Version: [{}]'.format(device['deviceID'], versionNumber))
        savePath = 'blobs/' + device['deviceID'] + '/' + device['deviceECID'] + '/release/' + versionNumber
        if not os.path.exists(savePath):
            os.makedirs(savePath)

        tssCall = subprocess.Popen(['./tsschecker_macos',
                                    '-d', device['deviceID'],
                                    '-e', device['deviceECID'],
                                    '--boardconfig', device['boardConfig'],
                                    '--buildid', buildID,
                                    '--save-path', savePath,
                                    '-s'], stdout=subprocess.PIPE)

        # The io module is a bit overkill but helps easily handle the stream from tssCall
        tssOutput = []
        for line in io.TextIOWrapper(tssCall.stdout, encoding='utf-8'):
            tssOutput.append(line.strip())

        ''' Checks console output for the `Saved shsh blobs!`
        string. While this works for now, tsschecker updates
        may break the check. It may be possible to check to
        see if the .shsh file was created and also check for
        the right file format. '''
        if 'Saved shsh blobs!' in tssOutput:
            self.logBlobsSaved(device, buildID, versionNumber)
            return True
        else:
            return False

    def logBlobsSaved(self, device, buildID, versionNumber):
        """ Taking a reference to a device dictionary, we can
         load the string `blobsSaved` from the database into
         a JSON object, append a newly saved version, and
         turn the JSON object back into a string and
         replace `blobsSaved` """

        oldBlobsSaved = json.loads(device['blobsSaved'])
        newBlobsSaved = {'releaseType': 'release', 'versionNumber': versionNumber, 'buildID': buildID}

        oldBlobsSaved.append(newBlobsSaved)

        device['blobsSaved'] = json.dumps(oldBlobsSaved)

        return

    def pushToDatabase(self):
        """ Loop through all of our devices and update their
        entries into the database. ECID is used as the value
        to update by, as it is the only unique device identifier."""

        print('\nUpdating database with newly saved blobs...')
        for device in self.devices:
            self.database['devices'].update(device, ['deviceECID'])
        print('Done updating database')

        return

def main():
    autotss()

if __name__ == "__main__":
    main()
Justins-MacBook-Pro:autotss justinwhite$ 


There is no blobs in the version folders of either devices. Removing the database file doesn't fix it.

**Comment by codsane** [comment]
Have you made sure to place the tsschecker_macos file in the same directory as autotss.py?

Right now the script doesn't check to make sure the tsschecker file is in the right spot, and it's also a bit confusing where it is supposed to be. I have a fix for this that'll be done tomorrow.

**Comment by ghost** [comment]
The devices.ini, autotss.py, and tsschecker_macos are all sitting in a folder together.  Hopefully you can fix this, it would be greatly appreciated by many. Especially for Apple fuck ups and when TSSsaver ironically goes down.

**Comment by codsane** [comment]
The changes I pushed *should* solve your problems. I've tried your devices.ini and haven't had any issues. The script will now check to make sure the blob files are actually there, and if they aren't, a log file will be saved in place of the blob file. Give the new version a shot and if you're still having issues, post the tsschecker_log.txt files.

![ss_ 2018-01-24 at 9 10 34 am](https://user-images.githubusercontent.com/12850297/35339547-7f34ef54-00e6-11e8-9c84-2d7bbfbe6982.png)
Blobs are now stored in `/blobs/device model/device ecid/version number/version build`. I noticed for some reason [there are iOS versions with the same version number, but different build IDs](https://user-images.githubusercontent.com/12850297/35339822-33065d38-00e7-11e8-9ead-376dbac5411a.png). For this reason I changed the way blobs are stored to make things easier.

**Comment by ghost** [comment]
![screen shot 2018-01-24 at 1 25 31 pm](https://user-images.githubusercontent.com/17184667/35352692-5fef3f72-010a-11e8-8c1c-e3bf2e83fb3a.png)

Make sure to include a step after uncompressing the tsschecker folder to rename it from "tsschecker_v212_mac_win_linux" to "tsschecker". 

Almost working, seems to be an issue with AutoTSS talking to TssChecker. :(

**Comment by codsane** [comment]
Hmm. Looks like you're on an older version of tsschecker. I'm going to assume you downloaded tsschecker from the repo, because the current version hosted there is version 212.

Can you try and download the latest version here: http://api.tihmstar.net/builds/tsschecker/tsschecker-latest.zip

Once that file is unzipped you should get a tsschecker-latest folder. This folder can then be placed in the same directory as autotss.py, as the script checks for any folder named 'tsschecker' or 'tsschecker-latest'.

Give that a try and let me know if the new version fixes your issue. I'll add it to my todo list to check the tsschecker file to see if you're on the right version.

**Comment by ghost** [comment]
Works now 100%

**Comment by ghost** [comment]
How would you go about making this run with cron...let's say every one minute...?

**Comment by codsane** [comment]
For something like that, there are tons of resources online as far as cron and scheduling jobs.

I'd recommend taking a look at: https://www.howtogeek.com/101288/how-to-schedule-tasks-on-linux-an-introduction-to-crontab-files/

**Comment by ktgvv** [comment]
Sorry for being off-topic, but I wrote cron jobs to execute `autotss.py`, and they seem to fail.

_`crontab -l`'s output:_
```
00 8,12,16,23  *  *  *    /usr/local/bin/python3 /Users/kvpb/bin/autotss/autotss.py 1>/tmp/stdout.log 2>&1
@reboot                   /usr/local/bin/python3 /Users/kvpb/bin/autotss/autotss.py 1>/tmp/stdout.log 2>&1
```

_`cat /tmp/stdout.log`'s output:_
```
tsschecker not found. Install or point to with -p
Get tsschecker here: https://github.com/encounter/tsschecker/releases
```

Could you write an example of cron job and pathnames?
