### ISSUE TITLE
AutoTSS

### ISSUE THREAD

**Issue by ghost** [codsane/autotss#6]
Wouldn't this only work for only 32bit device as 64bit devices require a signed baseband/sep to work? 

For this to become a automated process, wouldn't Apple eventually ban your ip from the polls just like they did to saurik?

**Comment by codsane** [comment]
autotss is merely a script that automates the use of tsschecker. If you have specific questions about saving blobs, you should ask at https://github.com/tihmstar/tsschecker.

For the amount of devices the average person has, no. If you're Saurik, maybe. But keep in mind the script doesn't make any actual requests to Apple's servers until there is a new firmware being signed. While the script may be running every five minutes using cron, there won't be a request to Apple's servers unless there are blobs to be saved.
